<?php
return array(
    'categories' => array(
        'generic' => array(
            'label' => 'Generic',
        ),
        'specific' => array(
            'label' => 'Specific',
        ),
    ),
    'dependents' => array(
        'select',
        'multiselect',
        'multi_checkbox',
        'radio',
        'gender',
        'profile_type',
    ),
    'advanced_fields' => array(
        'metrics',
        'recaptcha',
        'file_upload',
        'text_editor',
        'html_editor',
        'page_break',
        'section_break',
        'star_rating',
        'agreement'
    ),
    'user_analytics_fields' => array(
        'ua_ip_address',
        'ua_browser',
        'ua_browser_version',
        'ua_country',
        'ua_state',
        'ua_city',
        'ua_longitude',
        'ua_latitude',
    ),

    'fields' => array(
        // Generic
        'text' => array(
            'label' => 'Single-line Text Input',
            'category' => 'generic',
            'helper' => 'fieldText',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'textarea' => array(
            'label' => 'Multi-line Text Input',
            'category' => 'generic',
            'helper' => 'fieldTextarea',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('contains', 'starts_with', 'ends_with'),
        ),
        'select' => array(
            'label' => 'Select Box',
            'category' => 'generic',
            'helper' => 'fieldSelect',
            'multi' => false,
            'dependents' => true,
            'conditional_compare' => array('is', 'is_not'),
        ),
        'radio' => array(
            'label' => 'Radio Buttons',
            'category' => 'generic',
            'helper' => 'fieldSelect',
            'multi' => false,
            'dependents' => true,
            'conditional_compare' => array('is', 'is_not'),
        ),
        'checkbox' => array(
            'label' => 'Single Checkbox',
            'category' => 'generic',
            'helper' => 'fieldCheckbox',
            'multi' => false,
            'dependents' => true,
            'conditional_compare' => array('is'),
            'multiOptions' => array(
                '0' => 'Unselected',
                '1' => 'Selected',
            )
        ),
        'multiselect' => array(
            'label' => 'Multi Select Box',
            'category' => 'generic',
            'helper' => 'fieldMultiselect',
            'multi' => true,
            'dependents' => true,
            'conditional_compare' => array('contains', 'does_not_contain'),
        ),
        'multi_checkbox' => array(
            'label' => 'Multi Checkbox',
            'category' => 'generic',
            'helper' => 'fieldMultiselect',
            'multi' => true,
            'dependents' => true,
            'conditional_compare' => array('contains', 'does_not_contain'),
        ),
        'integer' => array(
            'label' => 'Integer',
            'category' => 'generic',
            'helper' => 'fieldText',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('is', 'is_not', 'greater_than', 'less_than'),
        ),
        'float' => array(
            'label' => 'Numbers',
            'category' => 'generic',
            'helper' => 'fieldText',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('is', 'is_not', 'greater_than', 'less_than'),
        ),
        'date' => array(
            'label' => 'Date',
            'category' => 'generic',
            'helper' => 'fieldDate',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('is', 'is_not', 'after', 'before'),
        ),
        'heading' => array(
            'label' => 'Heading',
            'category' => 'generic',
            'helper' => 'fieldHeading',
            'multi' => false,
            'dependents' => false,
        ),
        // Specific
        'profile_type' => array(
            'base' => 'select',
            'label' => 'Profile Type',
            'category' => false, // Hide this
        ),
        'first_name' => array(
            'base' => 'text',
            'label' => 'First Name',
            'category' => 'specific',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'last_name' => array(
            'base' => 'text',
            'label' => 'Last Name',
            'category' => 'specific',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'gender' => array(
            'base' => 'select',
            'label' => 'Gender',
            'category' => 'specific',
            'importOptions' => true,
            'conditional_compare' => array('is', 'is_not'),
        ),
        'birthdate' => array(
            'base' => 'date',
            'label' => 'Birthdate',
            'category' => 'specific',
//            'adminFormClass' => 'Fields_Form_Admin_Field_Birthdate',
            'helper' => 'fieldBirthdate',
            'conditional_compare' => array('is', 'is_not', 'after', 'before'),
        ),
        'about_me' => array(
            'base' => 'textarea',
            'label' => 'About Me',
            'category' => 'specific',
            'conditional_compare' => array('contains', 'starts_with', 'ends_with'),
        ),

        // Communications
        'website' => array(
            'base' => 'text',
            'label' => 'Website',
            'helper' => 'fieldYnWebsite',
            'category' => 'specific',
            'sql' => array(
                'type' => 'varchar',
                'length' => 255,
                'default' => '',
            ),
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'twitter' => array(
            'base' => 'text',
            'label' => 'Twitter',
            'category' => 'specific',
            'helper' => 'fieldTwitter',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'facebook' => array(
            'base' => 'text',
            'label' => 'Facebook',
            'category' => 'specific',
            'helper' => 'fieldFacebook',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'aim' => array(
            'base' => 'text',
            'label' => 'AIM',
            'category' => 'specific',
            'helper' => 'fieldAim',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'phone' => array(
            'base' => 'phone',
            'label' => 'Phone',
            'category' => 'specific',
            'id'=>'phone_num',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        // Location
        'city' => array(
            'base' => 'text',
            'label' => 'City',
            'category' => 'specific',
            'helper' => 'fieldText',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'country' => array(
            'base' => 'select',
            'label' => 'Country',
            'category' => 'specific',
            'helper' => 'fieldCountry',
            'conditional_compare' => array('is', 'is_not'),
            'conditional_multioptions' => true
        ),
        'zip_code' => array(
            'base' => 'integer',
            'label' => 'Zip Code',
            'category' => 'specific',
            'helper' => 'fieldZipCode',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        'location' => array(
            'base' => 'text',
            'label' => 'Location',
            'category' => 'specific',
            'helper' => 'fieldLocation',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),

        // Dating
        'relationship_status' => array(
            'base' => 'select',
            'label' => 'Relationship Status',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'single' => 'Single',
                'relationship' => 'In a Relationship',
                'engaged' => 'Engaged',
                'married' => 'Married',
                'complicated' => 'It\'s Complicated',
                'open' => 'In an Open Relationship',
                'widow' => 'Widowed',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'looking_for' => array(
            'base' => 'multi_checkbox',
            'label' => 'Looking For',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'friendship' => 'Friendship',
                'dating' => 'Dating',
                'relationship' => 'A Relationship',
                'networking' => 'Networking',
            ),
            'conditional_compare' => array('contains', 'does_not_contain'),
        ),
        'partner_gender' => array(
            'base' => 'multi_checkbox',
            'label' => 'Interested In',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'men' => 'Men',
                'women' => 'Women',
            ),
            'conditional_compare' => array('contains', 'does_not_contain'),
        ),
        'education_level' => array(
            'base' => 'select',
            'label' => 'Education',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'high_school' => 'High School',
                'some_college' => 'Some College',
                'associates' =>  'Associates Degree',
                'bachelors' => 'Bachelors Degree',
                'graduate' => 'Graduate Degree',
                'phd' => 'PhD / Post Doctoral',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'ethnicity' => array(
            'base' => 'multi_checkbox',
            'label' => 'Ethnicity',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'asian' => 'Asian',
                'black' => 'Black / African descent',
                'hispanic' => 'Latino / Hispanic',
                'pacific' => 'Pacific Islander',
                'white' => 'White / Caucasian',
                'other' => 'Other',
            ),
            'conditional_compare' => array('contains', 'does_not_contain'),
        ),
        'income' => array(
            'base' => 'select',
            'label' => 'Income',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                '25' => 'Less than $25,000',
                '25_35' => '$25,001 to $35,000',
                '35_50' => '$35,001 to $50,000',
                '50_75' => '$50,001 to $75,000',
                '75_100' => '$75,001 to $100,000',
                '100_150' => '$100,001 to $150,000',
                '150' => '$150,001+',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'occupation' => array(
            'base' => 'select',
            'label' => 'Occupation',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'admn' => 'Administrative / Secretarial',
                'arch' => 'Architecture / Interior design',
                'crea' => 'Artistic / Creative / Performance',
                'educ' => 'Education / Teacher / Professor',
                'mngt' => 'Executive / Management',
                'fash' => 'Fashion / Model / Beauty',
                'fina' => 'Financial / Accounting / Real Estate',
                'labr' => 'Labor / Construction',
                'lawe' => 'Law enforcement / Security / Military',
                'legl' => 'Legal',
                'medi' => 'Medical / Dental / Veterinary / Fitness',
                'nonp' => 'Nonprofit / Volunteer / Activist',
                'poli' => 'Political / Govt / Civil Service / Military',
                'retl' => 'Retail / Food services',
                'retr' => 'Retired',
                'sale' => 'Sales / Marketing',
                'self' => 'Self-Employed / Entrepreneur',
                'stud' => 'Student',
                'tech' => 'Technical / Science / Computers / Engineering',
                'trav' => 'Travel / Hospitality / Transportation',
                'othr' => 'Other profession',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'political_views' => array(
            'base' => 'select',
            'label' => 'Political Views',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'mid' => 'Middle of the Road',
                'far_right' => 'Very Conservative',
                'right' => 'Conservative',
                'left' => 'Liberal',
                'far_left' => 'Very Liberal',
                'anarchy' => 'Non-conformist',
                'libertarian' => 'Libertarian',
                'green' => 'Green',
                'other' => 'Other',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'religion' => array(
            'base' => 'select',
            'label' => 'Religion',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'agnostic' => 'Agnostic',
                'atheist' => 'Atheist',
                'buddhist' => 'Buddhist',
                'taoist' => 'Taoist',
                'catholic' => 'Christian (Catholic)',
                'mormon' => 'Christian (LDS)',
                'protestant' => 'Christian (Protestant)',
                'hindu' => 'Hindu',
                'jewish' => 'Jewish',
                'muslim' => 'Muslim',
                'spiritual' => 'Spiritual',
                'other' => 'Other',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'weight' => array(
            'base' => 'select',
            'label' => 'Weight',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'slender' => 'Slender',
                'average' => 'Average',
                'athletic' => 'Athletic',
                'heavy' => 'Heavy',
                'stocky' => 'Stocky',
                'little_fat' => 'A few extra pounds',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'zodiac' => array(
            'base' => 'select',
            'label' => 'Zodiac',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'capricorn' => 'Capricorn',
                'aquarius' => 'Aquarius',
                'pisces' => 'Pisces',
                'aries' => 'Aries',
                'taurus' => 'Taurus',
                'gemini' => 'Gemini',
                'cancer' => 'Cancer',
                'leo' => 'Leo',
                'virgo' => 'Virgo',
                'libra' => 'Libra',
                'scorpio' => 'Scorpio',
                'sagittarius' => 'Sagittarius',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),
        'eye_color' => array(
            'base' => 'select',
            'label' => 'Eye Color',
            'helper' => 'fieldOptions',
            'category' => 'specific',
            'multiOptions' => array(
                'black' => 'Black',
                'blue' => 'Blue',
                'brown' => 'Brown',
                'grey' => 'Grey',
                'green' => 'Green',
                'hazel' => 'Hazel',
            ),
            'conditional_compare' => array('is', 'is_not'),
        ),

        'interests' => array(
            'base' => 'textarea',
            'label' => 'Interests',
            'category' => 'specific',
            'helper' => 'fieldTextareaLinked',
            'conditional_compare' => array('contains', 'starts_with', 'ends_with'),
        ),

        'currency' => array(
            'base' => 'float',
            'label' => 'Currency',
            'category' => 'specific',
            'helper' => 'fieldCurrency',
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_Currency',
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
        ),
        // Advanced fields
        'metrics' => array(
            'label' => 'Metrics',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_Metrics',
            'dependents' => false,
            'conditional_compare' => array('is', 'is_not', 'greater_than', 'less_than'),
        ),
        'recaptcha' => array(
            'label' => 'reCAPTCHA',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_Recaptcha',
            'dependents' => false,
        ),
        'file_upload' => array(
            'label' => 'File Upload',
            'helper' => 'fieldFileUpload',
            'multi' => false,
            'dependents' => false,
            'conditional_compare' => array('is'),
            'multiOptions' => array(
                '0' => 'Empty',
                '1' => 'Not Empty',
            ),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_FileUpload'
        ),
        'text_editor' => array(
            'label' => 'Text Editor (predefined content)',
            'helper' => 'fieldTextEditor',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_TextEditor',
            'dependents' => false,
        ),
        'html_editor' => array(
            'label' => 'HTML Content (predefined content)',
            'helper' => 'fieldHTMLTextEditor',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_HTMLEditor',
            'dependents' => false,
        ),
        'page_break' => array(
            'label' => 'Page Break',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_PageBreak',
            'dependents' => false,
        ),
        'section_break' => array(
            'label' => 'Section Break',
            'helper' => 'fieldSectionBreak',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_SectionBreak',
            'dependents' => false,
        ),
        'star_rating' => array(
            'label' => 'Star Rating',
            'helper' => 'fieldStarRating',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_StarRating',
            'conditional_compare' => array('is', 'is_not', 'greater_than', 'less_than'),
            'dependents' => false,
            'multiOptions' => array(
                '1' => '1',
                '2' => '2',
                '3' => '3',
                '4' => '4',
                '5' => '5',
            ),
        ),
        'agreement' => array(
            'label' => 'Agreement',
            'helper' => 'fieldAgreement',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_Agreement',
            'dependents' => false,
        ),

        // User analytics fields
        'ua_ip_address' => array(
            'label' => 'IP Address',
            'helper' => 'fieldText',
            'multi' => false,
            'conditional_compare' => array('is', 'is_not', 'contains', 'starts_with', 'ends_with'),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_browser' => array(
            'label' => 'Browser',
            'helper' => 'fieldText',
            'multi' => false,
            'conditional_compare' => array('is', 'is_not'),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
            'multiOptions' => array(
                'Chrome' => 'Chrome',
                'Firefox' => 'Firefox',
                'Internet Explorer' => 'Internet Explorer',
                'Opera' => 'Opera',
                'Safari' => 'Safari',
            ),
        ),
        'ua_browser_version' => array(
            'label' => 'Browser Version',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_country' => array(
            'label' => 'Country',
            'helper' => 'fieldText',
            'multi' => false,
            'conditional_compare' => array('is', 'is_not'),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_state' => array(
            'label' => 'State',
            'helper' => 'fieldText',
            'multi' => false,
            'conditional_compare' => array('is', 'is_not'),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_city' => array(
            'label' => 'City',
            'helper' => 'fieldText',
            'multi' => false,
            'conditional_compare' => array('is', 'is_not'),
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_longitude' => array(
            'label' => 'Longitude',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
        'ua_latitude' => array(
            'label' => 'Latitude',
            'helper' => 'fieldText',
            'multi' => false,
            'adminFormClass' => 'Yndynamicform_Form_Admin_Field_UserAnalytics',
            'dependents' => false,
        ),
    ),
) ?>