<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Thanh
 * Date: 8/1/2016
 * Time: 1:48 PM
 */
class Yndynamicform_Installer extends Engine_Package_Installer_Module
{
    public function onInstall()
    {
        $this->_addHomePage();
        $this->_addFormsListingPage();
        $this->_addFormDetailsPage();
        $this->_addMyModeratedFormsPage();
        $this->_addMyEntriesPage();
        $this->_addListEntriesPage();
        $this->_addEntryDetailsPage();
        $this->_addEntryEditingPage();
        $this->_addFormConfirmationPage();
        return parent::onInstall(); // TODO: Change the autogenerated stub
    }

    public function _addHomePage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_index_index') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_index_index',
                'displayname' => 'YNC - Dynamic Form - Home Page',
                'title' => 'Home Page',
                'description' => 'This is the Dynamic form home page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.list-forms',
                'parent_content_id' => $main_middle_id,
                'order' => 1,
                'params' => '{"itemCountPerPage":"8"}',
            ));

            // main right
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'right',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_right_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-search',
                'parent_content_id' => $main_right_id,
                'order' => 1,
                'params' => '{"title":"Form Search"}',
            ));

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.categories',
                'parent_content_id' => $main_right_id,
                'order' => 2,
                'params' => '{"title":"Categories"}',
            ));
        }
    }

    public function _addFormsListingPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_index_list-forms') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_index_list-forms',
                'displayname' => 'YNC - Dynamic Form - Form Listing Page',
                'title' => 'Listing Forms',
                'description' => 'This is the form listing page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.list-forms',
                'parent_content_id' => $main_middle_id,
                'order' => 1,
                'params' => '{"itemCountPerPage":"8"}',
            ));

            // main right
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'right',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_right_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-search',
                'parent_content_id' => $main_right_id,
                'order' => 1,
                'params' => '{"title":"Form Search"}',
            ));

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.categories',
                'parent_content_id' => $main_right_id,
                'order' => 2,
                'params' => '{"title":"Categories"}',
            ));
        }
    }

    public function _addFormDetailsPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_form_detail') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_form_detail',
                'displayname' => 'YNC - Dynamic Form - Form Details Page',
                'title' => 'Form Details',
                'description' => 'This is the form details page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content
            $db -> insert('engine4_core_content', array(
                'page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.form-details',
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 2,
            ));

            //Insert Comments
            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.comments',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 3,
            ));

            // main right
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'right',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_right_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.list-related-forms',
                'parent_content_id' => $main_right_id,
                'order' => 1,
                'params' => '{"title":"Related Forms", "max":4}',
            ));
        }
    }

    public function _addMyModeratedFormsPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_index_my-moderated-forms') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_index_my-moderated-forms',
                'displayname' => 'YNC - Dynamic Form - My Moderated Forms Page',
                'title' => 'My Moderated Forms',
                'description' => 'This is my moderated forms page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.list-forms',
                'parent_content_id' => $main_middle_id,
                'order' => 1,
                'params' => '{"itemCountPerPage":"8"}',
            ));

            // main right
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'right',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_right_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-search',
                'parent_content_id' => $main_right_id,
                'order' => 1,
                'params' => '{"title":"Form Search"}',
            ));
        }
    }

    public function _addMyEntriesPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_entries_manage') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_entries_manage',
                'displayname' => 'YNC - Dynamic Form - My Entries Page',
                'title' => 'My Entries',
                'description' => 'This is my entries page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

    public function _addListEntriesPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_entries_list') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_entries_list',
                'displayname' => 'YNC - Dynamic Form - Entries List Page',
                'title' => 'Entries List',
                'description' => 'This is the entries list page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

    public function _addEntryDetailsPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_entries_view') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_entries_view',
                'displayname' => 'YNC - Dynamic Form - Entry Details Page',
                'title' => 'Entry Details',
                'description' => 'This is the entry details page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

    public function _addEntryEditingPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_entries_edit') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_entries_edit',
                'displayname' => 'YNC - Dynamic Form - Entry Editing Page',
                'title' => 'Entry Editings',
                'description' => 'This is the entry editing page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));
        }
    }

    public function _addFormConfirmationPage()
    {
        $db = $this -> getDb();

        // Check if it's already been placed
        $select = new Zend_Db_Select($db);
        $select -> from('engine4_core_pages') -> where('name = ?', 'yndynamicform_form_confirmation') -> limit(1);
        $info = $select -> query() -> fetch();

        if (empty($info)) {
            $db -> insert('engine4_core_pages', array('name' => 'yndynamicform_form_confirmation',
                'displayname' => 'YNC - Dynamic Form - Form Confirmation Page',
                'title' => 'Form Confirmation',
                'description' => 'This is the form confirmation page.',
                'custom' => 0,
            ));
            $page_id = $db -> lastInsertId('engine4_core_pages');

            // top
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'top',
                'parent_content_id' => null,
                'order' => 1,
            ));
            $top_id = $db -> lastInsertId('engine4_core_content');

            // top contents
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $top_id,
                'order' => 1,
            ));
            $top_middle_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.browse-menu',
                'parent_content_id' => $top_middle_id,
                'order' => 1,
            ));

            // main
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'main',
                'parent_content_id' => null,
                'order' => 2,
            ));
            $main_id = $db -> lastInsertId('engine4_core_content');

            // main middle
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'middle',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_middle_id = $db -> lastInsertId('engine4_core_content');

            // Insert content
            $db -> insert('engine4_core_content', array(
                'page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.form-details',
                'parent_content_id' => $main_middle_id,
                'order' => 1,
            ));

            $db->insert('engine4_core_content', array(
                'type' => 'widget',
                'name' => 'core.content',
                'page_id' => $page_id,
                'parent_content_id' => $main_middle_id,
                'order' => 2,
            ));

            // main right
            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'container',
                'name' => 'right',
                'parent_content_id' => $main_id,
                'order' => 2,
                'params' => '["[]"]',
            ));
            $main_right_id = $db -> lastInsertId('engine4_core_content');

            $db -> insert('engine4_core_content', array('page_id' => $page_id,
                'type' => 'widget',
                'name' => 'yndynamicform.list-related-forms',
                'parent_content_id' => $main_right_id,
                'order' => 1,
                'params' => '{"title":"Related Forms", "max":4}',
            ));
        }
    }
}
?>